#!/usr/bin/env bash

# Set up autograder files

eval `ssh-agent -s`
chmod 600 /autograder/source/id_rsa
ssh-add /autograder/source/id_rsa
ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

cd /autograder
git clone git@github.com:DanRunfola/D442.git

cp /autograder/submission/submission.py /autograder/D442/website/assignments/assignment2/assignment_2_grader/submission.py

cd /autograder/D442/website/assignments/assignment2/assignment_2_grader

python3 run_tests.py